language: node_js
matrix:
  include:
    - node_js: 14
    - node_js: "lts/*"
    - node_js: 10
  allow_failures:
    - node_js: 14
    - node_js: 10
install:
  - npm install
  - npm install --only=dev
script:
  - npm run coverage:ci
  - npm run coverage:upload
  - npm run build
cache:
  directories:
    - "node_modules"
    - "pki"
    - "certificates"
branches:
  only:
    - master
    - develop
    - alpha
    - beta
